# Generated by Django 5.2.8 on 2026-09-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biscuit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='biscuits/'),
        ),
    ]
